### ISSUE TITLE
Erro 500 ao buscar cliente com id inexistente

### ISSUE THREAD

**Issue by oliveiralex** [MarceloMachadoxD/APICrudClientesSpringBootJPA#1]
Caro Marcelo, meu nome é Alexandre e estou corrigindo sua atividade.

Seu trabalho já está aceito, parabéns! Mas para ficar 100%, favor incluir o tratamento de exceções. Está retornando erro 500 quando o id não existe. Tanto para a busca do cliente por id (GET), ao atualizar um cliente (UPDATE) e excluí-lo (DELETE).

Abraço e bons estudos

**Comment by MarceloMachadoxD** [comment]
Ajustada a annotation em ResourceExceptionHandler de @Configuration para @ControllerAdvice com isso as exceções passaram a ser capturadas corretamente
